### ISSUE TITLE
Pesky code coverage rules

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-customs-server#175]
Currently, custom server code coverage fails for levels 95% and lower. The majority of missing coverage is related to memcache error catch blocks and testing sqs queues, [details](https://coveralls.io/builds/10117078). More often then not, this could show the big RED fail on the PR.

What are your thoughts on
* Is there way to test catching memecache/sqs errors?
* Ignore coverage on files that are not critical to coverage
* Lower coverage to ~93% (my fav but kicks can until https://github.com/mozilla/fxa-customs-server/pull/174)
* Or other

@mozilla/fxa-devs

**Comment by philbooth** [comment]
I'm definitely not an expert on this repo, so I'm not sure my opinions count for much. But, since you ask, imho:

> Is there way to test catching memecache/sqs errors?

We should have some tests that mock the memcached layer and return error responses to test this stuff.

> * Ignore coverage on files that are not critical to coverage
> * Lower coverage to ~93% (my fav but kicks can until #174)

As much as I dislike code coverage as a metric of quality, knowingly allowing it to decrease smells bad to me. Better that we address the problem of testing the thing we don't know how to test, than settling for not testing that thing. Don't settle!

More generally, I think error paths are sometimes the most important thing to have automated test coverage for. The success paths often get regular testing with day-to-day usage. Error paths are like a closed petri dish for bad stuff to grow in.

**Comment by seanmonstar** [comment]
I just wanted to re-iterate about testing failure paths. Most of the time the stuff works, and that's good. But it can be easy to never actually hit a failing path, like memcached falling over, when manually testing. Best to be certain we handle all those cases.

Additionally, since this repo is our "security" or whatever service, I'd lean toward being stricter.

**Comment by rfk** [comment]
> Don't settle!

Well put, although until we can land #174 or something like it, this whole repo has become a bit of an exercise in settling...

I wonder if there's a small incremental refactor we can do that will help here, e.g. moving the storage-related code into its own module along the lines of [1], with its own more thorough test cases.  Might reduce the potential for throwing work away when we manage to land a more major refactor?

[1] https://github.com/mozilla/fxa-customs-server/blob/1e312bfd8bdbcb2618460fd09093eab88404eb48/lib/storage.js

**Comment by vbudhram** [comment]
Thanks guys! I was trying to figure out a good compromise between writing tests that would not be thrown away and getting coverage rules to pass. I think it is fair to add some tests for error paths on those modules, we should really have them.
