### ISSUE TITLE
FxA login is blocked for all the users during waiting period after SMS throttled limit is reached for any user

### ISSUE THREAD

**Issue by kkumari22** [mozilla/fxa-customs-server#186]
FxA login is blocked for all the users during waiting period after SMS throttled limit is reached for any user
![signin](https://cloud.githubusercontent.com/assets/16670573/24010449/27ce821e-0a35-11e7-83da-b397269ddc81.PNG)
![freshprofilenewfxaccount](https://cloud.githubusercontent.com/assets/16670573/24010454/2b7fe8b2-0a35-11e7-8c2e-75cdf3177d18.PNG)

Prerequisite: Existing SessionToken
STR:
1.Navigate to 'https://accounts.firefox.com/sms?service=sync'
2.Enter phone number in mobile number field and click send to send SMS
3.Repeat step 1 and 2 to send more than 5 messages to valid phone numbers within a span of an hour
4. After throttling (5 SMS) limit is reached, try to login on another os/device/browser with different or same  FxA credentials using url: https://accounts.firefox.com/sms?service=sync

Expected: On another machine other user logins shouldn't be blocked

Actual: FxA login is blocked for **all the users** during waiting period after SMS throttled limit is reached for any user

**Comment by rfk** [comment]
Thanks @kkumari22.  I suspect what's happening here is that the IP address has been blocked after exceeding the SMS-sending limit, meaning you can't do any account actions form that IP address until the block expires.  Can you confirm whether these logins were all from the same IP address?

**Comment by kkumari22** [comment]
No I am seeing this behavior even when I try on different machine with different IPs and different user logins. It seems that some flag is getting set on the server level which is blocking all the other user logins no matter which machine you try.

**Comment by vbudhram** [comment]
@kkumari22 The current sms rate limiting rules are

1) per phone number - 5 messages to any phone number from any email or ip address
2) per ip address - 5 messages sent from an ip address (blocks all actions from ip address)

When testing are you in an office? It could be possible that if you are on the same wifi all the traffic could be coming from one IP address, therefore leading all requests to get blocked. Something we could do it block based on the ip+email combination instead of just from ip. When implementing I tended towards being more strict, @rfk thoughts?

**Comment by rfk** [comment]
FWIW I can't reproduce the reported behaviour.  For me, sending more than 5 SMSs from one device results in all logins being blocked from that device, or from any devices that share the same IP (e.g. due to being on the same Wifi network).  But if I login on my phone, connected to a different network, then it does not get blocked.

> Something we could do it block based on the ip+email combination instead of just from ip.
> When implementing I tended towards being more strict

I'm happy with "more strict" as a default :-)

An alternative here would be to have sending too many SMSs block the IP address from sending any more SMSs, but allow it to still do other things such as logging in.  We've discussed a similar idea for email-sending before as well.  I'm not sure how yuck it would get in the code though...

**Comment by kkumari22** [comment]
I was testing it from different machines in the same office. Same Wifi network/IP could be the reason for this issue. I was expecting that throttling should be based on specific user Fx account.

I wish to do some more exploratory testing here but getting issue: https://github.com/mozilla/fxa-content-server/issues/4825.

**Comment by vladikoff** [comment]
from meeting: closing this for now, it works like other blocked actions by the customs server
